# Generated by Django 3.1.2 on 2021-04-23 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateCaseName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='用例名称')),
            ],
            options={
                'verbose_name': '导入用例名称',
                'verbose_name_plural': '导入用例名称',
                'db_table': 'fusion_generate_case_name',
            },
        ),
        migrations.CreateModel(
            name='GenerateCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=100, verbose_name='域名')),
                ('path', models.CharField(max_length=100, verbose_name='请求路径')),
                ('method', models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=100, verbose_name='请求方法')),
                ('request_type', models.CharField(choices=[('json', 'json'), ('form-data', 'form-data')], max_length=100, verbose_name='请求类型')),
                ('data', models.CharField(max_length=500, verbose_name='请求参数')),
                ('headers', models.CharField(max_length=100, verbose_name='请求头')),
                ('runTime', models.CharField(blank=True, max_length=100, verbose_name='请求时间')),
                ('argumentExtract', models.CharField(blank=True, max_length=100, verbose_name='参数提取')),
                ('expect_code', models.IntegerField(max_length=10, verbose_name='预期状态码')),
                ('expect_content', models.CharField(blank=True, max_length=200, verbose_name='断言内容')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='generateCase.generatecasename', verbose_name='用例名称')),
            ],
            options={
                'verbose_name': '导入接口用例',
                'verbose_name_plural': '导入接口用例',
                'db_table': 'fusion_generate_case',
            },
        ),
    ]
