# Generated by Django 3.1.2 on 2021-04-25 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generateCase', '0002_auto_20210423_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateCaseRunRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='运行时间')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generateCase.generatecasename', verbose_name='用例名称')),
            ],
            options={
                'verbose_name': '用例运行记录',
                'verbose_name_plural': '用例运行记录',
                'db_table': 'fusion_generate_run_record',
                'ordering': ['-create_time'],
            },
        ),
        migrations.RemoveField(
            model_name='generatecase',
            name='runTime',
        ),
        migrations.AlterField(
            model_name='generatecase',
            name='expect_code',
            field=models.IntegerField(verbose_name='预期状态码'),
        ),
        migrations.CreateModel(
            name='GenerateRunStepRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, verbose_name='请求的url')),
                ('http_method', models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=10, verbose_name='请求方式')),
                ('data', models.TextField(blank=True, null=True, verbose_name='提交的数据')),
                ('headers', models.TextField(blank=True, null=True, verbose_name='提交的header')),
                ('runTime', models.DateTimeField(auto_now=True, verbose_name='运行的时间')),
                ('return_code', models.CharField(max_length=10, verbose_name='返回的code')),
                ('return_content', models.TextField(blank=True, null=True, verbose_name='返回的内容')),
                ('return_cookies', models.TextField(blank=True, null=True, verbose_name='返回的cookies')),
                ('return_headers', models.TextField(blank=True, null=True, verbose_name='返回的headers')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generateCase.generatecaserunrecord', verbose_name='用例名称')),
            ],
            options={
                'verbose_name': 'api运行记录',
                'verbose_name_plural': 'api运行记录',
                'db_table': 'fusion_generate_step_record',
                'ordering': ['-create_time'],
            },
        ),
    ]
