# Generated by Django 3.1.2 on 2021-04-25 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generateCase', '0003_auto_20210425_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generaterunsteprecord',
            options={'ordering': ['create_time'], 'verbose_name': 'api运行记录', 'verbose_name_plural': 'api运行记录'},
        ),
        migrations.AddField(
            model_name='generaterunsteprecord',
            name='api',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='generateCase.generatecase', verbose_name='api'),
            preserve_default=False,
        ),
    ]
