# Generated by Django 3.1.2 on 2021-04-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateCase', '0004_auto_20210425_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaterunsteprecord',
            name='runTime',
            field=models.CharField(max_length=200, verbose_name='运行的时间'),
        ),
    ]
