# Generated by Django 3.1.2 on 2021-04-27 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generateCase', '0005_auto_20210425_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaterunsteprecord',
            name='api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='generateCase.generatecase', verbose_name='api'),
        ),
        migrations.AlterField(
            model_name='generaterunsteprecord',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='generateCase.generatecaserunrecord', verbose_name='用例名称'),
        ),
    ]
