# Generated by Django 3.1.2 on 2021-04-27 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generateCase', '0006_auto_20210427_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaterunsteprecord',
            name='api',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generateCase.generatecase', verbose_name='api'),
        ),
        migrations.AlterField(
            model_name='generaterunsteprecord',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generateCase.generatecaserunrecord', verbose_name='用例名称'),
        ),
    ]
