# Generated by Django 3.1.2 on 2021-05-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateCase', '0007_auto_20210427_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatecasename',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='标记删除'),
        ),
    ]
