# Generated by Django 3.1.2 on 2021-05-10 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generateCase', '0008_generatecasename_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatecase',
            name='argumentExtract',
            field=models.CharField(blank=True, max_length=2000, verbose_name='参数提取'),
        ),
        migrations.AlterField(
            model_name='generatecase',
            name='data',
            field=models.CharField(max_length=5000, verbose_name='请求参数'),
        ),
        migrations.AlterField(
            model_name='generatecase',
            name='expect_content',
            field=models.CharField(blank=True, max_length=2000, verbose_name='断言内容'),
        ),
        migrations.AlterField(
            model_name='generatecase',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step', to='generateCase.generatecasename', verbose_name='用例名称'),
        ),
        migrations.AlterField(
            model_name='generatecase',
            name='path',
            field=models.CharField(max_length=1000, verbose_name='请求路径'),
        ),
        migrations.AlterField(
            model_name='generatecase',
            name='request_type',
            field=models.CharField(choices=[('json', 'json'), ('data', 'data')], max_length=100, verbose_name='请求类型'),
        ),
    ]
