# Generated by Django 3.1.2 on 2021-05-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateCase', '0009_auto_20210510_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatecasename',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
    ]
