# Generated by Django 3.1.2 on 2022-04-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateCase', '0010_generatecasename_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatecase',
            name='remarks',
            field=models.CharField(blank=True, max_length=1000, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='generatecase',
            name='sleep_time',
            field=models.IntegerField(default=0, verbose_name='等待时间'),
        ),
        migrations.AddField(
            model_name='generatecasename',
            name='project',
            field=models.CharField(blank=True, max_length=100, verbose_name='系统'),
        ),
    ]
