# Generated by Django 3.1.2 on 2021-03-22 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formalbug',
            name='solve_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='解决时间'),
        ),
    ]
