# Generated by Django 3.1.2 on 2021-02-19 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiTest', '0002_auto_20210219_1354'),
        ('case', '0002_auto_20210219_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='api_list',
        ),
        migrations.AlterField(
            model_name='caseapilist',
            name='api',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apiTest.api'),
        ),
        migrations.AlterField(
            model_name='caseapilist',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='case.case'),
        ),
    ]
