# Generated by Django 3.1.2 on 2021-03-02 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_case_api_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='api_list',
        ),
    ]
