# Generated by Django 3.1.2 on 2021-04-08 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0005_remove_case_api_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseapilist',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_list', to='case.case'),
        ),
    ]
