# Generated by Django 3.1.2 on 2021-02-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=10, null=True, verbose_name='姓名'),
        ),
    ]
