# Generated by Django 3.1.2 on 2021-04-07 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiTest', '0003_runapirecord_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
    ]
