# Generated by Django 3.1.2 on 2022-06-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiTest', '0004_auto_20210407_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameterization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True, verbose_name='参数化名称')),
                ('expression', models.CharField(max_length=256, null=True, verbose_name='表达式')),
                ('example', models.CharField(max_length=256, null=True, verbose_name='示例')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '参数化表达式',
                'verbose_name_plural': '参数化表达式',
                'db_table': 'fusion_parameterization',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AlterField(
            model_name='api',
            name='request_type',
            field=models.CharField(choices=[('json', 'json'), ('data', 'data')], default='form-data', max_length=20, verbose_name='请求类型'),
        ),
    ]
